permalink:     /:year-:month-:day/:title.html
url:           http://uternet.github.io
author:        Lazy_Pig
paginate:      15
markdown:      redcarpet
redcarpet:
  extensions:  ["no_intra_emphasis", "fenced_code_blocks",  "tables","with_toc_data","strikethrough","underline","superscript"]
pygments:      true
safe:          true
auto:          true
